"""Frozen reason codes for A_sci / A_cap and controller actions (ICLR §4)."""

from __future__ import annotations

from enum import Enum


class ControllerAction(str, Enum):
    ENUMERATE = "enumerate"
    BIND = "bind"
    PROPOSE = "propose"
    COMMIT = "commit"
    EXECUTE = "execute"
    INVALIDATE = "invalidate"
    REINSTANTIATE = "reinstantiate"
    REJECT = "reject"
    STATUS = "status"


class ASciVerdict(str, Enum):
    APPLICABLE = "SCI_APPLICABLE"
    INAPPLICABLE_THEORY_MISMATCH = "SCI_INAPPLICABLE_THEORY_MISMATCH"
    INAPPLICABLE_REGION = "SCI_INAPPLICABLE_REGION"
    INAPPLICABLE_TEMPORAL_SCALE = "SCI_INAPPLICABLE_TEMPORAL_SCALE"
    INAPPLICABLE_HAZARD_CLASS = "SCI_INAPPLICABLE_HAZARD_CLASS"
    UNKNOWN_PENDING_THEORY = "SCI_UNKNOWN_PENDING_THEORY"


class ACapVerdict(str, Enum):
    REACHABLE = "CAP_REACHABLE"
    UNRESOLVED = "CAP_UNRESOLVED"
    UNREACHABLE_MISSING_ARTIFACT = "CAP_UNREACHABLE_MISSING_ARTIFACT"
    UNREACHABLE_CAPABILITY_UNAVAILABLE = "CAP_UNREACHABLE_CAPABILITY_UNAVAILABLE"
    UNREACHABLE_IMPL_MISSING = "CAP_UNREACHABLE_IMPL_MISSING"
    INCOMPATIBLE_SCHEMA = "CAP_INCOMPATIBLE_SCHEMA"
    INCOMPATIBLE_UNITS = "CAP_INCOMPATIBLE_UNITS"
    INCOMPATIBLE_CRS = "CAP_INCOMPATIBLE_CRS"
    INCOMPATIBLE_TIME = "CAP_INCOMPATIBLE_TIME"
    EDGE_INVALIDATED = "CAP_EDGE_INVALIDATED"


# Tri-state subcodes for UNRESOLVED (runtime probe not yet evaluated).
UNRESOLVED_SUBCODES = frozenset(
    {
        "CHECKPOINT_UNKNOWN",
        "LICENSE_UNPROBED",
        "PLATFORM_UNKNOWN",
        "GPU_UNKNOWN",
    }
)


APPLICABLE_ASCI = frozenset({ASciVerdict.APPLICABLE.value})
REACHABLE_ACAP = frozenset({ACapVerdict.REACHABLE.value})
